iot/iot/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('map/', include('map.urls', namespace='map')),
    path('account/', include('account.urls', namespace='account')),
    path('ml/', include('ml.urls', namespace='ml')),
    path('qa/', include('qa.urls', namespace='qa')),
    path('', include('pwa.urls')),
    re_path('.*', views.main),
]

iot/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
]

iot/ml/urls.py
from django.urls import path
from ml import views


app_name = 'ml'
urlpatterns = [
    path('', views.ml, name='ml'),
    path('train/', views.train, name='train'),
    path('isSurvive/', views.isSurvive, name='isSurvive'),
]

iot/qa/urls.py
from django.urls import path
from qa import views, webPush, qaCronJob, scrap


app_name = 'qa'
urlpatterns = [
    path('', views.qa, name='qa'),
    path('answer/', views.answer, name='answer'),
    path('cloud/', views.cloud, name='cloud'),
    path('subscription/', webPush.subscription, name='subscription'),
    path('notify/', qaCronJob.notify, name='notify'),
    path('saveKeyword/', views.saveKeyword, name='saveKeyword'),
    path('train/', views.train_model, name='train'),
    path('scrap/', scrap.scrapPTT, name='scrap'),
]

iot/qa/models.py
from django.db import models

# Create your models here.

iot/qa/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
# from django.http.response import HttpResponse
import pandas as pd
import numpy as np
from numpy.linalg import norm
import random
import gc
import pickle

#wordcloud
import jieba
import jieba.analyse
from wordcloud import WordCloud
from collections import Counter
import matplotlib.pyplot as plt
import json
import os
from account.models import User
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.preprocessing import MinMaxScaler
# 前處理
jieba.set_dictionary('dict.txt.big') #輸入繁體字典
Idf_vector = []
termindex = []
all_terms = []
termindexLen = 0
def preprocess(item):  ##定義前處理的function
    terms = [t for t in jieba.cut_for_search(item)]  ## 把全切分模式打開，可以比對的詞彙比較多
    all_terms.extend(terms)  ## 收集所有出現過的字
    return terms

def terms_to_vector(terms):  ## 定義把terms轉換成向量的function
    vector = np.zeros_like(termindex, dtype=np.float32)  ## 建立一條與termsindex等長、但值全部為零的向量
    for term in terms:
        if term in termindex: 
            idx = termindex.index(term)  ## 測試時如果有字沒有在索引中，需要保護
            vector[idx] += 1  ## 計算term frequency
    vector = vector * Idf_vector  ## 如果兩個vector的型別都是np.array，把兩條vector相乘，就會自動把向量中的每一個元素成在一起，建立出一條新的向量
    return vector   

def toint(num):
        return int(num)
     
path='qa/'
df_QA = pd.read_json(path+'Gossiping.json', encoding='utf8')# ProcessedData
temp_df = df_QA['tweets']
temp_df[temp_df==''] = 0
df_QA['tweets'] = temp_df
#10以下綠色以上黃色100以上爆 X是10以上噓XX是100以上
temp_df[temp_df=='X1'] = -10
temp_df[temp_df=='X2'] = -20
temp_df[temp_df=='X3'] = -30
temp_df[temp_df=='X4'] = -40
temp_df[temp_df=='X5'] = -50
temp_df[temp_df=='X6'] = -60
temp_df[temp_df=='X7'] = -70
temp_df[temp_df=='X8'] = -80
temp_df[temp_df=='X9'] = -90
temp_df[temp_df=='XX'] = -100
temp_df[temp_df=='爆'] = 100
df_QA['tweets'] = temp_df   
df_QA['tweets'] = df_QA['tweets'].apply(toint)
df_question = df_QA[['title', 'url', 'tweets']].copy()  ## 不要更動到原始的DataFrame
df_question.drop_duplicates(inplace=True)  ## 丟掉重複的資料
df_question['processed'] = df_question['title'].apply(preprocess)
print('preprocess...done')
termindex = list(set(all_terms))  ## 用set轉型可以將list中重複的部分拿掉
termindexLen = len(termindex)
Doc_Length = len(df_question)  ## 計算出共有幾篇文章
for term in termindex:  ## 對index中的詞彙跑回圈
    num_of_doc_contains_term = 0  ## 計算有機篇文章出現過這個詞彙
    for terms in df_question['processed']:
        if term in terms:
            num_of_doc_contains_term += 1
    idf = np.log(Doc_Length/num_of_doc_contains_term)  ## 計算該詞彙的IDF值
    Idf_vector.append(idf)

df_question['vector'] = df_question['processed'].apply(terms_to_vector)  ## 將上面定義的f
print('idf...done')
df_vector = df_question.copy()
del df_question
del df_QA
del all_terms
del temp_df
gc.collect()
    
@login_required    
def qa(request):
    keyword = request.user.keyword
    print(keyword)
    tweets = None
    if keyword:
        tweets = predict_tweets(keyword)  
    labels,values = hotKeyword(df_vector)
    context = {'answer':'', 'keyword':keyword, 'tweets':tweets
               , 'labels':labels, 'values':values}
    template = 'qa/qa.html'
   
    return render(request, template, context)

@login_required
def answer(request): 
    context = {}
    # 把檔案讀出來
    # 我們這次只會使用到title跟url這兩個欄位 
    df_ans = retrieve(str(request.GET['q']))
    print('retrieve...done')
    result = []
    tweets = None
    for q in df_ans[['title','url']].values:
        result.append({'title':q[0],'url':q[1]})
    print('result message...done')  
    keyword = request.user.keyword
    
    if keyword:
        tweets = predict_tweets(keyword) 
    labels,values = hotKeyword(df_vector) 
    context.update({'aswer':result, 'keyword':keyword, 'tweets':tweets
                    , 'labels':labels, 'values':values})
    
    return render(request, 'qa/qa.html',context)

def cloud(request):
    all_terms_cloud = []
    with open('qa/stops.txt', 'r', encoding='utf8') as f:  
        stops = f.read().split('\n') 
    stops.append('問卦')
    stops.append('https')
    stops.append('jpg')
    for n in range(100):
        stops.append(str(n))
    stops.append('\n')
    stops.append('\n\n')
    stops.append('\nRe')
    stops.append('新聞')
    # 把檔案讀出來
    df_QA = pd.read_json('qa/Gossiping.json', encoding='utf8')# ProcessedData
    # 我們這次只會使用到title跟url這兩個欄位
    df_question = df_QA[['title', 'content']].copy()  ## 不要更動到原始的DataFrame
    df_question.drop_duplicates(inplace=True)  ## 丟掉重複的資料
    
    def preprocess_extract(item):  ##定義前處理的function
        terms = [t for t in jieba.analyse.extract_tags(item, topK=20) if t not in stops]  ## 把全切分模式打開，可以比對的詞彙比較多
        all_terms_cloud.extend(terms)  ## 收集所有出現過的字
        return terms
    df_question['processed'] = df_question['title'].apply(preprocess_extract)
    cloud_pct = plt.imread('cloud.jpg')
    wordcloud = WordCloud(background_color='white',
                              mask=cloud_pct,
                              font_path="qa/simsun.ttf")  ##做中文時務必加上字形檔
    wordcloud.generate_from_frequencies(frequencies=Counter(all_terms_cloud))
    
#     plt.figure(figsize=(15,15))
#     plt.imshow(wordcloud, interpolation="bilinear")
#     plt.axis("off")
#     plt.show()
    wordcloud.to_file('static/qa/img/month_terms.jpg')
    return redirect('qa/qahtml')
    
    
    
def cosine_similarity(vector1, vector2):  ## 定義cosine相似度的計算公式
    score = np.dot(vector1, vector2)  / (norm(vector1) * norm(vector2))
    return score


def preprocessSentence(item):  ##定義前處理的function
    terms = [t for t in jieba.cut_for_search(item)]  ## 把全切分模式打開，可以比對的詞彙比較多
    return terms



def retrieve(testing_sentence, return_num=3):  ## 定義出檢索引擎
    testing_vector = terms_to_vector(preprocessSentence(testing_sentence))  ## 把剛剛的前處理、轉換成向量的function，應用在使用者輸入的問題上
    score_dict = {}  ## 準備把每一個問題對應到使用者問題的cosine分數記錄下來
    df_vector_sorted = df_vector.sort_index(ascending=True)
    for idx, vec in enumerate(df_vector_sorted['vector']):  ## 計算每一個問題與使用者問題的cosine分數
        score = cosine_similarity(testing_vector, vec)
        score_dict[idx] = score
    idxs = np.array(sorted(score_dict.items(), key=lambda x:x[1], reverse=True))[:return_num, 0]  ##排序出最相關的前N個問題的row index
#     print(df_vector[:5])
#     print(df_vector_sorted[:5])
#     print(df_vector_sorted.loc[0,['vector']][0])
#     for i in idxs:
#         print(i)
#         print(score_dict[i])
#     print('cosine:')
#     print(cosine_similarity(df_vector_sorted.loc[348,['vector']][0],testing_vector))
#     print(df_vector_sorted.loc[idxs, ['title', 'url','processed']])
    return df_vector_sorted.loc[idxs, ['title', 'url']]

@login_required
def saveKeyword(request):
    '''
    TODO:把這個function做成ajax
    '''
    user = request.user
    keyword = request.GET['keyword']
    users = User.objects.filter(fullName=user.fullName)
    for user in users:
        user.keyword = keyword
        user.save()
    print(keyword)
    tweets = predict_tweets(keyword)
    labels,values = hotKeyword(df_vector) 
    context = {'answer':'', 'keyword':keyword, 'tweets':tweets
               , 'labels':labels, 'values':values}
    template = 'qa/qa.html'

    return render(request, template, context)



def train_model(request):
    scaler = MinMaxScaler()
    scaler.fit(df_vector['tweets'].values.reshape(-1,1))
    y_train = scaler.transform(df_vector['tweets'].values.reshape(-1,1))
    temp = df_vector['vector'].copy()
    def tolist(ndarray):
        return list(ndarray)
    temp = temp.apply(tolist)
    temp = list(temp.values)
    x = np.array(temp)
    xgr = XGBRegressor(n_estimators=150, learning_rate=0.01,n_jobs = 2)# gamma=0, subsample=0.85, colsample_bytree=0.8, max_depth=20, min_child_weight = 11
    X_train, X_test, y_train, y_test = train_test_split(x, y_train, test_size=0.2, random_state=42)
    xgr.fit(X_train, y_train,eval_set=[(X_train, y_train), (X_test, y_test)], early_stopping_rounds=100)
    print('open file..\n')
    trainedReggresor = open('xgbmodel.pickle', 'wb')
    print('done\n')
    print('xgbmodel pickle...')
    pickle.dump(xgr, trainedReggresor)
    trainedReggresor.close()
    print('done')
    
    print('open file..\n')
    trainscaler = open('scaler.pickle', 'wb')
    print('done\n')
    print('scaler pickle...')
    pickle.dump(scaler, trainscaler)
    trainscaler.close()
    print('done')
    return redirect('qa/qa.html')


def predict_tweets(keyword):
    path = 'qa/'
    with open(path+'xgbmodel.pickle', 'rb') as f:
        trainedReggresor = pickle.load(f)
    with open(path+'scaler.pickle', 'rb') as f2:
        trainedscaler = pickle.load(f2)
    terms = [t for t in jieba.cut_for_search(keyword)]
    print(terms)
    question = terms_to_vector(terms)
    print(question.sum())
    print(cosine_similarity(question,terms_to_vector(['柯文','哲' ])))
    question = question.reshape(1,termindexLen)
    print(question)
    print(trainedReggresor)
    tweets = trainedReggresor.predict(question).reshape(-1,1)
    print(tweets)
    print(trainedscaler)
    tweets = trainedscaler.inverse_transform(tweets)
    tweets = int(tweets)
    print(tweets)
    
    return tweets
    
    
    
def hotKeyword(df_vector):
    path='qa/'
    with open(path+'stops.txt', 'r', encoding='utf8') as f:  
        stops = f.read().split('\n') 
    stops.append('\n')
    stops.append('\t')
    df_QA_sort = df_vector.sort_values(by=['tweets'],ascending=False)
    df_QA_sort = df_QA_sort[:100]
    top100vectors = list(df_QA_sort['processed'].values)
    top100terms = []
    for item in top100vectors:
        for i in item:  
            if i not in stops: 
                top100terms.append(i)
    count = Counter(top100terms).most_common(10)

iot/qa/templates/qa/qa.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% load pwa %}
{% block css %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'qa/css/carousel.css' %}" type="text/css">
{% endblock %}
{% block heading %}QA APP{% endblock %}
{% block head %}
<!-- all for PWA -->
<!-- <link rel="manifest" href="/manifest.json"> -->
<link rel="icon" href="{% static 'main/img/favicon.png' %}">
<!-- theme-color defines the top bar color (blue in my case) -->
<meta name="theme-color" content="#FFF"/>

<!-- Add to home screen for Safari on iOS -->
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="default"/>
<meta name="apple-mobile-web-app-title" content="民代拍檔"/>
<link rel="apple-touch-icon" href="{% static 'main/img/144x144.png' %}"/>

<!-- Add to home screen for Windows -->
<meta name="msapplication-TileImage" content="{% static 'main/img/144x144.png' %}"/>
<meta name="msapplication-TileColor" content="#000000"/> 
{% endblock %}
{% block content %}
<header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">PTT 定時報</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main:main' %}">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
          <form class="form-inline mt-2 mt-md-0" method=get action="{% url 'qa:answer' %}">
            <input class="form-control mr-sm-2" id="q" name="q" type="text" placeholder="Question.." aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ask</button>
          </form>
        </div>
      </nav>
    </header>

    <main role="main">


      <!-- Marketing messaging and featurettes
      ================================================== -->
      <!-- Wrap the rest of the page in another container to center all the content. -->

      <div class="container marketing">
            <form  style="text-align:center; padding:3%;"  method=get action="{% url 'qa:saveKeyword' %}">
             <div class="form-group md-form">
                <label><h2>keyword</h2></label>
                <input class="form-control form-control-lg " id="keyword" name="keyword" type="text" placeholder="{{ keyword|default_if_none:'enter your keyword..' }}" aria-label="Search">
             </div>
                <p><button class="btn  btn-secondary my-2 my-sm-0" type="submit">Save</button></p>   
            </form>
            
        <!-- START THE FEATURETTES -->

        <hr >

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">最相關答覆. <span class="text-muted">前3名.</span></h2>
            {% for a in aswer %}              
                  <p class="lead">{{ a.title }}</p>
                  <a class="lead">{{ a.url }}</a>
            {% endfor %}
          </div>
<!--           <div class="col-md-5"> -->
<!--             <img class="featurette-image img-fluid mx-auto" src="{% static 'qa/img/month_terms.jpg' %}" alt="Generic placeholder image"> -->
<!--           </div> -->
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'qa/img/qa.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>

        <hr ><!-- class="featurette-divider" -->

        <div class="row featurette">
          <div class="col-md-5 order-md-2">
            <h2 class="featurette-heading">本月標題關鍵字. </h2>
            <h3 class="featurette-heading"><span class="text-muted">文字雲.</span></h3>
            <h3 class="featurette-heading"><span class="text-muted">*每月初更新一次.</span></h3>          
          </div>
          <div class="col-md-5 order-md-1">
            <img class="featurette-image img-fluid mx-auto" src="{% static 'qa/img/month_terms.jpg' %}" alt="Generic placeholder image">
          </div>
        </div>

        <hr >

        <div class="row featurette">
          <div class="col-md-7">
            <h2 class="featurette-heading">關鍵字推噓數</h2>
            <h3><span class="text-muted">與當天資料做比較關鍵字熱門程度</span></h3>
            <p class="lead"><h1>{{ tweets }}</h1></p>
          </div>
          <div class="col-md-5">
            <canvas class="my-4 img-fluid mx-auto" id="myChart" ></canvas><!-- width="900" height="380" -->
          </div>
        </div>

        <hr class="featurette-divider">

        <!-- /END THE FEATURETTES -->

      </div><!-- /.container -->


      <!-- FOOTER -->
      <footer class="container">
        <p class="float-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017-2018 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
      </footer>
    </main>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    {% if user.is_authenticated %}
      <script src="{% static 'qa/js/webPush.js' %}"></script>
    {% endif %}
<!--     <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
<!--     <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script> -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
          labels: [{% for label in labels %}'{{ label }}'{% if not forloop.last %}, {% endif %}{% endfor %}
          ],
          datasets: [{
            data: [{% for value in values %}'{{ value }}'{% if not forloop.last %}, {% endif %}{% endfor %}
            ],
            backgroundColor:'rgba(255, 99, 132, 0.2)',
            borderColor:'rgba(255,99,132,1)',
            borderWidth: 1,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
        	title:{
        		display:true,
        		text:'Top 100 熱門文章出現最多次的字詞'
        	},
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
{% endblock %}
{% block script %}
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}