iot/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

iot/iot/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('map/', include('map.urls', namespace='map')),
    path('account/', include('account.urls', namespace='account')),
    path('ml/', include('ml.urls', namespace='ml')),
    path('qa/', include('qa.urls', namespace='qa')),
    path('', include('pwa.urls')),
    re_path('.*', views.main),
]

iot/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
]

iot/map/urls.py
from django.urls import path
from map import views


app_name = 'map'
urlpatterns = [
    path('', views.map, name='map'),
    path('getAddress/', views.getAddress, name='getAddress'),
    path('getData/', views.getData, name='getData'),
] 

iot/ml/urls.py
from django.urls import path
from ml import views


app_name = 'ml'
urlpatterns = [
    path('', views.ml, name='ml'),
    path('train/', views.train, name='train'),
    path('isSurvive/', views.isSurvive, name='isSurvive'),
]

iot/qa/urls.py
from django.urls import path
from qa import views, webPush, qaCronJob, scrap


app_name = 'qa'
urlpatterns = [
    path('', views.qa, name='qa'),
    path('answer/', views.answer, name='answer'),
    path('cloud/', views.cloud, name='cloud'),
    path('subscription/', webPush.subscription, name='subscription'),
    path('notify/', qaCronJob.notify, name='notify'),
    path('saveKeyword/', views.saveKeyword, name='saveKeyword'),
    path('train/', views.train_model, name='train'),
    path('scrap/', scrap.scrapPTT, name='scrap'),
]

iot/main/models.py
from django.db import models


iot/main/views.py
from django.shortcuts import render

def main(request):
    return render(request, 'main/main.html')


iot/main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>{% block heading %}{% endblock %}</title>
    <meta charset="utf-8">
<!--     <link rel="stylesheet" href="{% static 'main/css/cover.css' %}"> -->
    {% block css %}{% endblock %}
    {% block head %}{% endblock %}
  </head>
  <body style="text-align:center">
    
    {% block content %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block script %}{% endblock %}
  </body>
</html>

iot/main/templates/main/main.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% block css %}
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> 
    <link rel="canonical" href="https://getbootstrap.com/docs/4.1/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

<!--     Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'main/css/cover.css' %}" type="text/css">
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
{% endblock %}
{% block heading %}QA APP{% endblock %}
{% block head %}
<!-- all for PWA -->
<!-- <link rel="manifest" href="/manifest.json"> -->
<link rel="icon" href="{% static 'main/img/favicon.png' %}">
<!-- theme-color defines the top bar color (blue in my case) -->
<meta name="theme-color" content="#FFF"/>

<!-- Add to home screen for Safari on iOS -->
<meta name="apple-mobile-web-app-capable" content="yes"/>
<meta name="apple-mobile-web-app-status-bar-style" content="default"/>
<meta name="apple-mobile-web-app-title" content="ptt tweet"/>
<link rel="apple-touch-icon" href="{% static 'main/img/144x144.png' %}"/>

<!-- Add to home screen for Windows -->
<meta name="msapplication-TileImage" content="{% static 'main/img/144x144.png' %}"/>
<meta name="msapplication-TileColor" content="#000000"/> 
{% endblock %}
{% block content %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand">IoT</h3>
      <nav class="nav nav-masthead justify-content-center">
        {% include 'main/menu.html' %}
      </nav>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">Wellcome</h1>
    <p class="lead">this is a side project that the teacher ask us to do in the IoT class. there are three applications in this website</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Cover template for <a href="https://getbootstrap.com/">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
  </footer>
</div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
{% endblock %}
{% block script %}
<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<!--     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}

iot/main/templates/main/main_old.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>IoT</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/owl.carousel.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/cssl/owl.theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/component.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/normalize.css' %}" />
    <link href="{% static 'main/css/pace-theme-flash.css' %}" rel="stylesheet" type="text/css"
        media="screen" />
    <!-- BEGIN CORE CSS FRAMEWORK -->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrapTheme.css' %}">
    <link href="{% static 'main/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- END CORE CSS FRAMEWORK -->
    <!-- BEGIN CSS TEMPLATE -->
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'main/css/magic_space.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'main/css/responsive.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'main/css/animate.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- END CSS TEMPLATE -->
    <script type="text/javascript" src="{% static 'main/js/jquery-1.8.3.min.js' %}"></script>
    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="{% static 'main/js/slider1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/slider2.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/settings.css' %}" media="screen" />
  </head>
  <body>
    <div class="main-wrapper">
        <header id="ha-header" class="ha-header ha-header-hide ">
            <div class="ha-header-perspective">
                <div class="ha-header-front navbar navbar-default">
                    <div class="compressed">
                        <div class="navbar-header">
                            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle"
                                type="button">
                                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                                    class="icon-bar"></span><span class="icon-bar"></span>
                            </button>
                            <a href="#" class="navbar-brand compressed">
                                <h2>IoT</h2></a>
                        </div>
                        <div class="navbar-collapse collapse">
                            {% include 'main/menu.html' %}
                            
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </div>
        </header>
        <div class="section ha-waypoint" data-animate-down="ha-header-hide" data-animate-up="ha-header-hide">
            <div role="navigation" class="navbar navbar-transparent navbar-top">
                <div class="container">
                    <div class="compressed">
                        <div class="navbar-header">
                            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle"
                                type="button">
                                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                                    class="icon-bar"></span><span class="icon-bar"></span>
                            </button>
                            <a href="#" class="navbar-brand">
                                <h1>IoT</h1>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav navbar-right">
                                {% include 'main/menu.html' %}
                            </ul>
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!--BEGIN SLIDER -->
            <div class="tp-banner-container">
                <div class="tp-banner" id="home">
                    <ul>
                        <!-- SLIDE  -->
                        <li data-transition="fade" data-slotamount="5" data-masterspeed="700">
                            <!-- MAIN IMAGE -->
                            <img src="{% static 'main/img/slide_one.jpg' %}" alt="slidebg1" data-bgfit="cover" data-bgposition="center center"
                                data-bgrepeat="no-repeat"> 
                            <!-- LAYERS -->
                            <div class="tp-caption mediumlarge_light_white_center sft tp-resizeme slider" data-x="center"
                                data-hoffset="0" data-y="80" data-speed="500" data-start="800" data-easing="Power4.easeOut"
                                data-endspeed="300" data-endeasing="Power1.easeIn" data-captionhidden="off" style="z-index: 6">
                                <h2 class="text-white custom-font title ">
                                    We Create<br>
                                    Map & Data
                                    <br />
                                    Analysis for Customers</h2>
                            </div>
                            <div class="tp-caption sfb slider tp-resizeme slider" data-x="center" data-hoffset="0"
                                data-y="320" data-speed="800" data-start="1000" data-easing="Power4.easeOut"
                                data-endspeed="300" data-endeasing="Power1.easeIn" data-captionhidden="off" style="z-index: 6">
                                <a href="{% url 'map:map' %}" class="btn btn-info btn-lg  btn-large m-r-10">See Map Now</a>
                            </div>
                        </li>
                           
                    </ul>
                    <div class="tp-bannertimer">
                    </div>
                </div>
                <div style="position: absolute; top: 469px; margin-top: -20px; left: 20px;" class="tp-leftarrow tparrows default"></div>
                <div style="position: absolute; top: 469px; margin-top: -20px; right: 20px;" class="tp-rightarrow tparrows default hidearrows"></div>
            </div>
            <!--END SLIDER
    
  -->
        </div>
       
    </div>
    <script src="{% static 'main/js/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/pace.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/jquery.unveil.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/owl.carousel.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/waypoints.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.nicescroll.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.appear.js' %}"></script>
    <script src="{% static 'main/js/jquery.animateNumbers.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'main/js/core.js' %}"></script>
  </body>
  
</html>

iot/main/templates/main/menu.html
<!-- <ul id="menu" class="nav navbar-nav navbar-right"> -->
      <a class="nav-link active" href="{% url 'main:main' %}">首頁</a>
      <a class="nav-link " href="{% url 'map:map' %}">地圖</a>
      <a class="nav-link " href="{% url 'ml:ml' %}">ML應用</a>
      <a class="nav-link " href="{% url 'qa:qa' %}">QA</a>
      {% if user.is_authenticated %}
      <a class="nav-link " href="{% url 'account:logout' %}">登出 ({{ user.username }})</a>
      {% else %}
      <a class="nav-link " href="{% url 'account:register' %}">註冊</a>
      <a class="nav-link " href="{% url 'account:login' %}">登入</a>
      {% endif %}
<!--     </ul> -->
    