iot/iot/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls', namespace='main')),
    path('map/', include('map.urls', namespace='map')),
    path('account/', include('account.urls', namespace='account')),
    path('ml/', include('ml.urls', namespace='ml')),
    path('qa/', include('qa.urls', namespace='qa')),
    path('', include('pwa.urls')),
    re_path('.*', views.main),
]

iot/map/urls.py
from django.urls import path
from map import views


app_name = 'map'
urlpatterns = [
    path('', views.map, name='map'),
    path('getAddress/', views.getAddress, name='getAddress'),
    path('getData/', views.getData, name='getData'),
] 

iot/ml/urls.py
from django.urls import path
from ml import views


app_name = 'ml'
urlpatterns = [
    path('', views.ml, name='ml'),
    path('train/', views.train, name='train'),
    path('isSurvive/', views.isSurvive, name='isSurvive'),
]

iot/map/models.py
from django.db import models

class Light(models.Model):
    time = models.DateTimeField(blank=True, null=True)
    value = models.IntegerField()
    address = models.CharField(max_length=128)
    
    def __str__(self):
        return '(' + self.address + '):' +  str(self.value)
    
    class Meta:
        ordering = ['address', 'time']

iot/map/views.py
from django.shortcuts import render
from map.models import Light
from django.http.response import HttpResponse
import json
from django.utils import timezone
from datetime import date

from django.contrib.auth.decorators import login_required

@login_required
def map(request):
    '''
    Show map in the map page
    '''
    lights = Light.objects.all()
    
    context = {'lights':lights}
    return render(request, 'map/indexShowAddress.html', context)

@login_required
def getAddress(request):
    lights = Light.objects.all()
    lightAddresses = lights.values('address').order_by('address').distinct('address')
    lightAddresses = list(lightAddresses)
    lightAddressList = []
    for address in lightAddresses:
        lightAddressList.append(address['address'])

    return HttpResponse(json.dumps({'lightAddresses':lightAddressList}), content_type='application/json')

@login_required
def getData(request):
    address = request.GET.get('address').strip()
    #address = '中興大學'
    if not address:
        return HttpResponse('')
    lights = Light.objects.filter(address__icontains=address)
    lightAddresses = lights.values('value', 'time', 'address').order_by('time')
    lightAddresses = list(lightAddresses)   
    
    for light in lightAddresses:
        light['time'] = date.strftime(timezone.localtime(light['time']), '%Y-%m-%d %H:%M:%S')  # 為了移除秒數(因為丟到form會顯示秒數) 
    
    return HttpResponse(json.dumps({'lightAddresses':lightAddresses}), content_type='application/json')


iot/map/templates/map/indexShowAddress.html
{% load staticfiles %}
<html>
<head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
         /* Always set the map height explicitly to define the size of the div
        * element that contains the map. */
         #map {
             height: 100%;
         }
         /* Optional: Makes the sample page fill the window. */
         html, body {
             height: 100%;
             margin: 0;
             padding: 0;
         }
    </style>
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/owl.carousel.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/cssl/owl.theme.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/component.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/normalize.css' %}" />
    <link href="{% static 'main/css/pace-theme-flash.css' %}" rel="stylesheet" type="text/css"
        media="screen" />
    <!-- BEGIN CORE CSS FRAMEWORK -->
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrapTheme.css' %}">
    <link href="{% static 'main/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- END CORE CSS FRAMEWORK -->
    <!-- BEGIN CSS TEMPLATE -->
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'main/css/magic_space.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'main/css/responsive.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'main/css/animate.min.css' %}" rel="stylesheet" type="text/css" />
    <!-- END CSS TEMPLATE -->
    <script type="text/javascript" src="{% static 'main/js/jquery-1.8.3.min.js' %}"></script>
    <!-- SLIDER REVOLUTION 4.x SCRIPTS  -->
    <script type="text/javascript" src="{% static 'main/js/slider1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/slider2.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'main/css/settings.css' %}" media="screen" />
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> -->
    <!--include the jQuery library-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
        <!-- <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script> -->     
        <!--include the highcharts library-->
        <script src="https://code.highcharts.com/highcharts.js"></script>
        <!--<script src="http://code.highcharts.com/stock/highstock.js"></script>
        <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>-->
</head>
<body>
   <div class="main-wrapper">
        <header id="ha-header" class="ha-header ha-header-hide ">
            <div class="ha-header-perspective">
                <div class="ha-header-front navbar navbar-default">
                    <div class="compressed">
                        <div class="navbar-header">
                            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle"
                                type="button">
                                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                                    class="icon-bar"></span><span class="icon-bar"></span>
                            </button>
                            <a href="#" class="navbar-brand compressed">
                                <h2>IoT</h2></a>
                        </div>
                        <div class="navbar-collapse collapse">
                            {% include 'main/menu.html' %}
                            
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </div>
        </header>
        <div class="section ha-waypoint" data-animate-down="ha-header-hide" data-animate-up="ha-header-hide">
            <div role="navigation" class="navbar navbar-transparent navbar-top">
                <div class="container">
                    <div class="compressed">
                        <div class="navbar-header">
                            <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle"
                                type="button">
                                <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span><span
                                    class="icon-bar"></span><span class="icon-bar"></span>
                            </button>
                            <a href="#" class="navbar-brand">
                                <h1>IoT</h1>
                        </div>
                        <div class="navbar-collapse collapse">
                            <ul class="nav navbar-nav navbar-right">
                                {% include 'main/menu.html' %}
                            </ul>
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </div>
            <!--BEGIN SLIDER -->
            <div class="tp-banner-container">
                <div class="tp-banner" id="home">                                   
                            <div id="map" class="tp-caption mediumlarge_light_white_center sft tp-resizeme slider" data-x="center"
                                data-hoffset="0" data-y="80" data-speed="500" data-start="800" data-easing="Power4.easeOut"
                                data-endspeed="300" data-endeasing="Power1.easeIn" data-captionhidden="off" style="z-index: 6">
                                <!-- <h2 class="text-white custom-font title ">
                                    We Create<br>
                                    Brands & Marketing
                                    <br />
                                    Strategies for Customers</h2> -->
                            </div>
                    <div class="tp-bannertimer">
                    </div>
                </div>
                <div style="position: absolute; top: 469px; margin-top: -20px; left: 20px;" class="tp-leftarrow tparrows default"></div>
                <div style="position: absolute; top: 469px; margin-top: -20px; right: 20px;" class="tp-rightarrow tparrows default hidearrows"></div>
            </div>
            <!--END SLIDER
    
  -->
        </div>
       
    </div>
    <!-- <div id="map"></div> -->
    <script>
        
        var map;
        var geocoder;
        var myAddress = [];
        var myCenter = { lat: 24.1209446, lng: 120.6742369 };
       
        function initMap() {
            geocoder = new google.maps.Geocoder();
            map = new google.maps.Map(document.getElementById('map'), {
                center: myCenter,
                title: '中興大學',
                zoom: 8
            });

            $.ajax({
                url: "{% url 'map:getAddress' %}",
                data: '',
                dataType: 'json',
                //success: getDataSuccess
            }).done(function(data) {
            	 console.log('getAddress success!!');
            	 //console.log(data['lightAddresses']);
            	 for (i = 0; i < data['lightAddresses'].length; i++) {
                  codeAddress(data['lightAddresses'][i].toString());
                  console.log(data['lightAddresses'][i].toString());
               }
             })
             .fail(function() {
                  alert('連線失敗');
             });

        }

        function getDataSuccess(data) {
            for (i = 0; i < data.length; i++) {
                codeAddress(data['lightAddresses'][i].toString());
                console.log(data['lightAddresses'][i].toString());
            }
        }


function codeAddress(address1){
    geocoder.geocode( { 'address':address1}, function(results, status) {
      if (status == 'OK') {
        var title_link = "<a href='https://www.google.com.tw/search?q="+address1+"+google&oq="+address1+"+google&sourceid=chrome&ie=UTF-8'>"+address1+"</a>";
        var title_map = "<a href='https://www.google.com.tw/search?q="+address1+"+google+map'>"+address1+"</a>";
        var redirect_link = "<?php header('Location: https://www.google.com.tw/search?q="+address1+"+google+map'>"+address1+"');?>";
        var html = '<a href="http://localhost:80/gmap_sample/getData.php?address='+address1+'">'+address1+'</a>';
        var html4 = '<html><head></head><body><div id='+address1+'>'+address1+'</div></body></html>';
        map.setCenter(results[0].geometry.location);
        var marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            title : address1
        }); // end maker
        var infowindow = new google.maps.InfoWindow({
            content: html4
        });

  
        marker.addListener('click', function() {
            initialize(address1);
            infowindow.open(map, marker);
        });
      } // end if 
      else {
        alert('Geocode was not successful for the following reason: ' + status);
      } // end else
    }); // end geocoder
  } // end function


    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6aa_nOKRwbB-_mO3Q__iuUAVC0zuzWps&callback=initMap"
            async defer></script>
    <script>
    {% include 'map/highchart.js' %}
    </script>
    <script src="{% static 'main/js/bootstrap.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/pace.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/jquery.unveil.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/owl.carousel.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'main/js/waypoints.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.nicescroll.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'main/js/jquery.appear.js' %}"></script>
    <script src="{% static 'main/js/jquery.animateNumbers.js' %}" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'main/js/core.js' %}"></script>
</body>
</html>